### PR TITLE
Updating version to 2.0.0

### PR DESCRIPTION
**Pull request by Amit3200**
Major Version update for PoA.
Use following `package.json` for PoA runs:
``` json
{
  "private": true,
  "scripts": {
    "test": "make test"
  },
  "devDependencies": {
    "@percy/cli": "1.27.0-alpha.0",
    "@percy/webdriver-utils": "1.27.0-alpha.0"
  }
}

```

### CODE REVIEW

**Review by itsjwala — COMMENTED** [review]
lets update package.json as well, since this will go in master now

**Comment by Amit3200** [comment]
> lets update package.json as well, since this will go in master now

@itsjwala I also wanted to update the `package.json`, if its fine I will update it as it is pinning the particular CLI alpha version and will be merged to master that is why I was little concerned.

**Comment by itsjwala** [comment]
@Amit3200 not an issue, this codebase is used only for development purpose. 

example repo should contain stable release.

**Comment by Amit3200** [comment]
Closing this as for consistent PR and release

**Pull request closed without merging**
